# Generated by Django 4.0.5 on 2022-06-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
